name: Push to go package system on tag



on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false
      - name: prod proxy
        run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{ github.ref_name }}
